spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cheongmarudb # docker-compose 내 mysql 서비스와 연결
    username: cheongmaru                      # MySQL 사용자 이름
    password: cheongmarupw                    # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버 클래스

  jpa:
    hibernate:
      ddl-auto: create      # 서버 시작 시 Entity 기반 테이블 자동 생성 (운영 시에는 update 또는 none 권장)
    show-sql: true          # 실행되는 SQL 쿼리를 콘솔에 출력
    properties:
      hibernate:
        format_sql: true    # 쿼리를 보기 좋게 포맷팅
    open-in-view: false     # OSIV 비활성화. API 요청-응답 사이에 영속성 컨텍스트 열어두지 않음

server:
  port: 8080  # 애플리케이션이 실행될 포트


jwt:
  secret: OXJvb210b25fdW5pdi5jaHVuZ2J1a25hdGlvbmFsdW5pdmVyc2l0eS5wcm9qZWN0LnRlYW0x
  expiration: 3600000  # 1시간 (단위: 밀리초)


oauth:
  kakao:
    client-id: 594d8ec9028eac2ae44a733fcb3e7c52
    redirect-uri: http://localhost:8080/api/auth/kakao
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me